### PR TITLE
create fr.md for doc contribute

### PR DESCRIPTION
**Pull request by Kittycatou**
No words on patrons ?

### CODE REVIEW

**Comment by joostdecock** [comment]
Good point. We should add something about that. Would you like to do it?

**Comment by Kittycatou** [comment]
No problem

**Comment by joostdecock** [comment]
> No problem

Great work :) I've updated the phrasing a bit. It was mentioning our switch from donations to patrons, but as that happened over a year ago, it's a bit of an outdated reference.

Could you do something similar in French?

**Comment by joostdecock** [comment]
> The content following "setting:" shouldn't be translated, right ?

Correct. It should be left in English. This is the documentation for the different draft options (units, language, paperless, sa, and so on). The system uses this to pull up the correct documentation when a user requests it on the draft page.

So leave it as is :)

**Pull request merged**
