### PR TITLE
update fr.md for Simon doc

### PR DESCRIPTION
**Pull request by Kittycatou**
Finished translation (that was a long one -.- )

### CODE REVIEW

**Comment by joostdecock** [comment]
You deserve a lot of praise for this 😇 and perhaps a promotion? I've been mulling over on how to pitch this idea to you, so I'll just come out and say it: Would you like to be responsible for diversity and inclusion within the freesewing project?

Diversity [is a big issue in open source](https://www.wired.com/2017/06/diversity-open-source-even-worse-tech-overall/) and we need to actively work towards inclusion. However, the road to hell is paved with good intentions. It's all too easy to forget about these things when you have a to-do list that makes you feel like drowning.

You've already pointed out that assuming the API docs don't need to be translated was wrong. I would feel a lot better knowing that these important issues were looked after by someone who is better at them than I am.

**Comment by Kittycatou** [comment]
I am quite surprise by your reaction to my few comments but also honoured by your idea. Actually I am not familiar with these diversity and inclusion issues so I won't pretend to be better at them than you are at all.

Concerning translating the API docs, it's a bit by intellectual laziness that I thought of it first. But I'm pretty confident on the fact that :
- some French people can be reluctant to speak English 
- you can be good in algorithmic and suck at English

I don't know if I have what it takes to lighten the load on your shoulders, but I can give you my small helping hand in this project. I will do what I can.

**Comment by joostdecock** [comment]
:) It doesn't have to be a big deal from one moment to the next. But much like having a code of conduct  can help create a friendly environment, having someone who is tasked with inclusion/diversity  sends a message about what kind of community we want to be.

We could do a few things right away:

 - Our [code of conduct](https://beta.freesewing.org/en/docs/about/code-of-conduct#point-of-contact) says to report problematic behavior to me. I imagine it would lower the bar for women if there it said to report to report problems to Joost or Catherine 
 - Same thing with [our contact page](https://beta.freesewing.org/en/docs/contact#e-mail)
 - We could publish a blog post to announce it  (you can write it in French if you'd like ;) )

But I don't want to push you in any way. The only thing I'd really like to see you do is tell me when I'm doing it wrong.

**Comment by Kittycatou** [comment]
Well, I think I can do that. Maybe we could just mention my name in the next monthly roundup.
I will update the contact and code of conduct pages as you suggest.

**Comment by joostdecock** [comment]
> Well, I think I can do that

:smile: 

> Maybe we could just mention my name in the next monthly roundup.

Will do!

> I will update the contact and code of conduct pages as you suggest.

Only if you think that's a good idea.

Also: I will merge this now

**Review by joostdecock — APPROVED** [review]

**Pull request merged**
